name: ax6 OpenWRT Build

on:
#  schedule:
#    - cron: 5 6 * * 0
  push:
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-24.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Show system
      run: |
        echo -e "Total CPU cores\t: $(nproc)"
        cat /proc/cpuinfo | grep 'model name'
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        swap-size-mb: 1024
        temp-reserve-mb: 512
        root-reserve-mb: 4608
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
    - name: Checkout
      uses: actions/checkout@main
    - name: Init build dependencies
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install build-essential clang flex bison g++ gawk \
        gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev \
        python3-setuptools rsync swig unzip zlib1g-dev file wget \
        llvm python3-pyelftools libpython3-dev aria2 jq qemu-utils ccache rename \
        libelf-dev device-tree-compiler libgmp3-dev libmpc-dev libfuse-dev jq
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "Asia/Shanghai"
    - name: prepare
      run: |
        bash ./scripts/prepare.sh
    - name: Get Architecture
      working-directory: ${{ github.workspace }}/openwrt
      run: |
        tag_name=$(curl --silent "https://api.github.com/repos/openwrt/openwrt/releases/latest" | jq -r .tag_name)
        echo "tag_name=${tag_name}" >>$GITHUB_ENV
    - name: Make Download
      run: |
        cd openwrt
        make download -j50
    - name: Make Defconfig
      run: |
        cd openwrt
        make defconfig
    - name: Compile Openwrt
      id: compileopenwrt
      continue-on-error: true
      run: |
        cd openwrt
        #echo | make kernel_oldconfig -j$(($(nproc) + 1)) 
        IGNORE_ERRORS=1 make -j$(($(nproc) + 1))
        echo $?
    - name: If Error
      if: steps.compileopenwrt.outcome == 'failure'
      run: |
        cat openwrt/.config
        echo '================================================================'
        cd openwrt && make -j1 V=s
    - name: Print Disk Space After
      run: df -h
    - name: Organize files
      id: organize
      run: |
        rm -rf ./artifact/
        mkdir -p ./artifact/
        mv openwrt/bin/targets/qualcommax/ipq807x/openwrt-*.ubi ./artifact/
        mv openwrt/bin/targets/qualcommax/ipq807x/openwrt-* ./artifact/
        mv openwrt/bin/targets/qualcommax/ipq807x/config.buildinfo ./artifact/
        cd ./artifact/
        ls -Ahl
    - name: Upload artifact
      uses: actions/upload-artifact@main
      with:
        name: OpenWRT_${{ env.tag_name }}
        path: ./artifact/

    - name: Create release
      id: create_release
      uses: ncipollo/release-action@v1.14.0
      with:
        name: redmi-ax6-${{ env.tag_name }}
        allowUpdates: true
        tag: ${{ env.tag_name }}
        replacesArtifacts: true
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: ./artifact/*
